version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - relationships:
              arguments:
                field: customer_id
                to: ref('stg_customers')
              config:
                severity: warn
  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
              config:
                severity: warn
  - name: stg_inventory