version: 2
sources:
  - name: raw
    database: KIWIMART_DB
    schema: RAW
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: stores
      - name: inventory
      - name: returns